### ISSUE TITLE
app fails on Samsung Galaxy S3 and Asus Nexus 7 / Google Tablet

### ISSUE THREAD

**Issue by jasonm23** [don/phonegap-p2p#2]
Just trying to get this working with the Samsung Galaxy S3, and also on a Nexus 7 tablet.

On both devices the app fails at launch, any ideas I could try? 

So far I've tried updating the plugin to the latest version from the phonegap nfc plugin repo, and various versions of phonegap and cordova, always with the same result.

Hope you can help me solve this one.

Thanks for your effort creating these examples.

**Comment by don** [comment]
The peer to peer support has been neglected.  It worked well until Android Beam was introduced.  I can't remember if you need to disable beam or compile with an old sdk target.

I need to support peer to peer for an Android to Arduino NFC project so I'll be looking at this code again soon.

**Comment by jasonm23** [comment]
Thanks, I'll see if I can figure it out too.
